# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Canopy < Formula
  desc "Terminal UI for managing parallel AI coding agents"
  homepage "https://github.com/isacssw/canopy"
  version "0.5.0"
  license "MIT"

  depends_on "tmux"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/isacssw/canopy/releases/download/v0.5.0/canopy_darwin_amd64.tar.gz"
      sha256 "90e7ba6afaf3a77bee542f1949ef306901b68a77852dc0b470219e55bc415305"

      define_method(:install) do
        bin.install "canopy"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/isacssw/canopy/releases/download/v0.5.0/canopy_darwin_arm64.tar.gz"
      sha256 "8e3a390723b6c3f344f9cb81c7e3a62e7264f891785745e77d53bc8cdd4c4ace"

      define_method(:install) do
        bin.install "canopy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/isacssw/canopy/releases/download/v0.5.0/canopy_linux_amd64.tar.gz"
      sha256 "aecfac0d7798cfd44467733522aa15b1588680dd568b672baa3cfb7a4d84a408"
      define_method(:install) do
        bin.install "canopy"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/isacssw/canopy/releases/download/v0.5.0/canopy_linux_arm64.tar.gz"
      sha256 "04dcb8891f3a4c1ca2f53e73b20ceab1d781e4714afdd780dc5e637ff3087332"
      define_method(:install) do
        bin.install "canopy"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/canopy --version")
  end
end
