# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Canopy < Formula
  desc "Terminal UI for managing parallel AI coding agents"
  homepage "https://github.com/isacssw/canopy"
  version "0.6.1"
  license "MIT"

  depends_on "tmux"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/isacssw/canopy/releases/download/v0.6.1/canopy_darwin_amd64.tar.gz"
      sha256 "ed03984764dd5fb264058d49eb7a5b8205ac8cd4d3127cc42bf7202b892fcbc0"

      define_method(:install) do
        bin.install "canopy"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/isacssw/canopy/releases/download/v0.6.1/canopy_darwin_arm64.tar.gz"
      sha256 "71639207ad2ec61da6e3cd61f5e62eb0d809cdba18e531bd0183ebe99be2726a"

      define_method(:install) do
        bin.install "canopy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/isacssw/canopy/releases/download/v0.6.1/canopy_linux_amd64.tar.gz"
      sha256 "e8bcc900f943e820b25a33d3a1d0169dccabe2986d51aa3a2bafae00008680e4"
      define_method(:install) do
        bin.install "canopy"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/isacssw/canopy/releases/download/v0.6.1/canopy_linux_arm64.tar.gz"
      sha256 "bd1ac115c43ed52a7c9a708cabff0a59deda00a52bc60e4e4e58a6e76f256274"
      define_method(:install) do
        bin.install "canopy"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/canopy --version")
  end
end
