# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Canopy < Formula
  desc "Terminal UI for managing parallel AI coding agents"
  homepage "https://github.com/isacssw/canopy"
  version "0.3.0"
  license "MIT"

  depends_on "tmux"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/isacssw/canopy/releases/download/v0.3.0/canopy_darwin_amd64.tar.gz"
      sha256 "f47db4d4697e6b4c481b691bd456ff45591ade25c618df1fb84504d1e10fbab5"

      define_method(:install) do
        bin.install "canopy"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/isacssw/canopy/releases/download/v0.3.0/canopy_darwin_arm64.tar.gz"
      sha256 "6bb0247b52bd977d785856e42b245ed2e4ac35dadb9b622f0bc162cf59357404"

      define_method(:install) do
        bin.install "canopy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/isacssw/canopy/releases/download/v0.3.0/canopy_linux_amd64.tar.gz"
      sha256 "16fc2ab6cec3ae66d318665c5c6ce526019ab704560f74a16bb6dcc29d894b16"
      define_method(:install) do
        bin.install "canopy"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/isacssw/canopy/releases/download/v0.3.0/canopy_linux_arm64.tar.gz"
      sha256 "24457d1858a0bdca614f34c77d60eca113d6629caad1476ec333ad14a1cc3e29"
      define_method(:install) do
        bin.install "canopy"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/canopy --version")
  end
end
